apiVersion: v1
kind: ConfigMap
metadata:
  name: capabilities-test-config
  labels:
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
data:
  cap_apiversions: 
{{ .Capabilities.APIVersions | toYaml | indent 4 }}

  cap_kubeversion: 
{{ .Capabilities.KubeVersion | toYaml | indent 4 }}  

{{- if .Capabilities.APIVersions.Has "batch/v1" }}      
  apiversion_detected: "batch/v1"
{{- else }}
  apiVersion_not_detected: "N/A"  
{{- end }}