apiVersion: v1
kind: ConfigMap
metadata:
  name: "argocd-test-config-{{ .Release.Name }}"
  labels:
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
data:
  test_key: {{ .Values.argocdTest.config.test_key }}