apiVersion: v1
kind: ConfigMap
metadata:
  name: lookup-test-config
  labels:
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
data:
  {{- $secret := (lookup "v1" "Secret" argocd argocd-secret) }}
  {{- if $secret }} ## rotate secrets with secretProvider help if exists
  secret-was-looked-up: "true" ## created in the sws-secrets-provider helm chart
  {{- else }}
  secret-was-looked-up: "false"
  {{- end }}